development:
  server: "https://fayeserverssbleague.herokuapp.com/faye"
  secret_token: "bluemagic"
test:
  server: "https://fayeserverssbleague.herokuapp.com/faye"
  secret_token: "bluemagic"
production:
  server: "https://fayeserverssbleague.herokuapp.com/faye"
  secret_token: "bluemagic"
  signature_expiration: 86400 # one hour
