# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f1d7108b84fd20f9ef47a148a0908082f0b03a23d8c11cefd32617c49c3a9b4ad8ef04b8633a86ede9dfdd1ee23fdd65bd90e59fbbb1be0fe8a572d6559e8a4f

test:
  secret_key_base: e5880c955db78c5e24c45effbaa0b09b9b2b545eb37b92b925f29af70d004c582298eaeb4a475b8e8ba7b9e3be0aea91c7845c88a262d3983658fc89e6857f6b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
